-@ignore = true
-index ||= false
-view  ||= :normal

%p== Cutting out the middleman is one of the best things you can do to improve service, satisfaction, price and overall system efficiency. In supply chain theory there is a concept called the #{link_to "Bullwhip Effect", "http://en.wikipedia.org/wiki/Bullwhip_effect"}. It says that the more middlemen you introduce into a supply chain the less efficient it can be. As a distributor makes an order he causes demand to whip up as seen the upstream supply chain members and even when obeying the most efficient ordering algorithm, the upstream member has to order more than the demand, leading to a amplification of the demand. Left unchecked this demand can get out of hand and become a giant surplus.

%p== Middlemen are not only inefficient, but they are also costly. Consider how many people are required to deliver a piece of real estate(e.g. your home for example) to you. You have the 2 realtors and their brokerages, 2 lawyers and their firms, a house inspector, a pest inspector, two banks, a title insurance company, an appraiser, and city, county, state, and federal government agents. <strong>Each of these people makes enough money to do real estate transactions full time</strong> (except the government, they do not know how to make money.). People are the largest expense of any company, and they certainly are the largest expense of any real estate transaction. If you can get rid of any of these middlemen or decrease their compensation you can save a lot of money on a real estate transaction. One example to look into, if you are selling your home, is #{link_to "Flat-fee MLS", "http://en.wikipedia.org/wiki/Flat_fee_MLS"} listing. With a flat listing fee you can save up to 3% of the sale price of your home.

%p Middlemen can also leave you less satisfied. When is the last time you bought a new car and felt satisfied? With the way car dealers haggle, you know that someone else out there is getting a better price, and you always have to weigh the stress induced by haggling you before you get into it. The fact is car dealers make their money by selling cars in volume and since they buy their cars at a fixed price from the manufacturers, they care a lot about selling each car for as much as they can. It would be great if we could cut out the car dealerships and buy cars from an automotive department store? This is what CarMax has done with used cars. They sell all makes of used cars at a reasonable sticker price and they do not haggle. This leaves their customers feeling more satisfied: they got the same deal anyone else would have gotten, and they did not have deal with the stress of haggling.

%p==The effect of the Internet that has done the most good for humanity has been removing middlemen. It is has become so easy to set up an online store that many factories and manufacturers are beginning to sell their goods online. Even if they haven't begun to do so, the #{link_to "new manufacturers", "http://www.pololu.com"} are.

%p==A lot of great businesses were founded with the idea of taking out the middleman. GEICO takes out the middleman of having an insurance agent. The Foam Factory #{link_to "sells cheap memory foam mattresses direct", "blog/memory-foam-mattress"}. If you are thinking of starting a business, one of the surest ways to achieve customer goodwill is to take out a middleman. When you take out a middleman, customers go from spending more money to less. When you save customers money, they love you.

%p What middlemen have you dealt with recently and how could you have avoided it?