name: docs

on:
  - push
  - workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v16
      - run: nix build
      - if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: result/multi
          fqdn: ryantm.com
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
